### ISSUE TITLE
error: input is too short

### ISSUE THREAD

**Issue by Blobikium** [faizanasghar43/DataSet-creator-RVC#2]
when there is more than 1 .wav file the script outputs:
### Instant Dataset Maker
provided to you by youtube.com/@rawonions
Read the README.txt file for more info!

Loading...
Error: Input is too short (n=378888) for frame_length=432000
Temporary directory deleted

**Comment by faizanasghar43** [comment]
You'll have to go with one file each time, it was written in that for files bigger than 10 mins.
